package ssh

import (
	"crypto"
	"encoding/pem"

	gossh "github.com/malivvan/crypto/ssh/internal"
)

// PublicKey is an abstraction of different types of public keys. It is an
// alias of the protocol implementation's type, so keys parsed or produced by
// this package round-trip without conversion.
type PublicKey = gossh.PublicKey

// CryptoPublicKey is the underlying crypto.PublicKey of a [PublicKey], as
// returned by its CryptoPublicKey method.
type CryptoPublicKey = gossh.CryptoPublicKey

// A Signer can create signatures that verify against a public key.
type Signer = gossh.Signer

// An AlgorithmSigner is a [Signer] that also supports specifying an algorithm
// to use for signing.
type AlgorithmSigner = gossh.AlgorithmSigner

// A MultiAlgorithmSigner is an [AlgorithmSigner] that can advertise the
// algorithms it supports.
type MultiAlgorithmSigner = gossh.MultiAlgorithmSigner

// The Permissions type holds fine-grained permissions that are specific to a
// user or a specific authentication method for a user. Permissions, except for
// "source-address", must be enforced in the server application layer, after
// successful authentication.
type Permissions = gossh.Permissions

// Public key algorithms names. These values can appear in PublicKey.Type,
// ClientConfig.HostKeyAlgorithms, or Signature.Format.
const (
	KeyAlgoED25519   = gossh.KeyAlgoED25519
	KeyAlgoSKED25519 = gossh.KeyAlgoSKED25519
)

// ParseAuthorizedKey parses a public key from an authorized_keys file used in
// OpenSSH according to the sshd(8) manual page.
func ParseAuthorizedKey(in []byte) (out PublicKey, comment string, options []string, rest []byte, err error) {
	return gossh.ParseAuthorizedKey(in)
}

// ParsePublicKey parses an SSH public key formatted for use in
// the SSH wire protocol according to RFC 4253, section 6.6.
func ParsePublicKey(in []byte) (out PublicKey, err error) {
	return gossh.ParsePublicKey(in)
}

// MarshalAuthorizedKey serializes key for inclusion in an OpenSSH
// authorized_keys file. The return value ends with newline.
func MarshalAuthorizedKey(key PublicKey) []byte {
	return gossh.MarshalAuthorizedKey(key)
}

// NewPublicKey takes an *ed25519.PublicKey or an Ed25519 public key type
// returned from [crypto/x509.ParsePKIXPublicKey] and returns a PublicKey,
// suitable for calling Verify.
func NewPublicKey(key interface{}) (PublicKey, error) {
	return gossh.NewPublicKey(key)
}

// NewSignerFromKey takes an *ed25519.PrivateKey or a crypto.Signer with an
// Ed25519 public key and returns a Signer.
func NewSignerFromKey(key interface{}) (Signer, error) {
	return gossh.NewSignerFromKey(key)
}

// NewSignerFromSigner takes any [crypto.Signer] and returns a [Signer]. This
// can be used, for instance, to use a hardware-backed Ed25519 key as an SSH
// host or user key.
func NewSignerFromSigner(signer crypto.Signer) (Signer, error) {
	return gossh.NewSignerFromSigner(signer)
}

// NewSignerWithAlgorithms takes a signer that does not advertise the
// algorithms it supports and returns a MultiAlgorithmSigner for the given
// algorithms.
func NewSignerWithAlgorithms(signer AlgorithmSigner, algorithms []string) (MultiAlgorithmSigner, error) {
	return gossh.NewSignerWithAlgorithms(signer, algorithms)
}

// NewCertSigner returns a Signer that signs with the given Certificate,
// allowing an Ed25519 key to be used as an SSH certificate. The certificate
// must be signed by signer for the result to be usable.
func NewCertSigner(cert *Certificate, signer Signer) (Signer, error) {
	return gossh.NewCertSigner(cert, signer)
}

// ParsePrivateKey returns a Signer from a PEM encoded (unencrypted) private
// key. It supports Ed25519 private keys in PKCS#8 and OpenSSH formats, as
// generated by ssh-keygen.
func ParsePrivateKey(pemBytes []byte) (Signer, error) {
	return gossh.ParsePrivateKey(pemBytes)
}

// ParsePrivateKeyWithPassphrase returns a Signer from a PEM encoded encrypted
// private key, decrypted with the given passphrase.
func ParsePrivateKeyWithPassphrase(pemBytes, passphrase []byte) (Signer, error) {
	return gossh.ParsePrivateKeyWithPassphrase(pemBytes, passphrase)
}

// ParseRawPrivateKey returns a private key from a PEM encoded private key. It
// supports Ed25519 private keys in PKCS#8 and OpenSSH formats. If the key is
// passphrase protected, the [PassphraseMissingError] is returned.
func ParseRawPrivateKey(pemBytes []byte) (interface{}, error) {
	return gossh.ParseRawPrivateKey(pemBytes)
}

// ParseRawPrivateKeyWithPassphrase returns a private key decrypted with the
// given passphrase.
func ParseRawPrivateKeyWithPassphrase(pemBytes, passphrase []byte) (interface{}, error) {
	return gossh.ParseRawPrivateKeyWithPassphrase(pemBytes, passphrase)
}

// MarshalPrivateKey returns a PEM block with the private key serialized in the
// OpenSSH format.
func MarshalPrivateKey(key crypto.PrivateKey, comment string) (*pem.Block, error) {
	return gossh.MarshalPrivateKey(key, comment)
}

// MarshalPrivateKeyWithPassphrase returns a PEM block holding the encrypted
// private key.
func MarshalPrivateKeyWithPassphrase(key crypto.PrivateKey, comment string, passphrase []byte) (*pem.Block, error) {
	return gossh.MarshalPrivateKeyWithPassphrase(key, comment, passphrase)
}

// FingerprintSHA256 returns the user presentation of the key's fingerprint as
// described by RFC 4716 section 4.
func FingerprintSHA256(pubKey PublicKey) string {
	return gossh.FingerprintSHA256(pubKey)
}

// FingerprintLegacyMD5 returns the user presentation of the key's fingerprint
// as described by RFC 4716 section 4. MD5 fingerprints are legacy: prefer
// [FingerprintSHA256] and use this only to display a fingerprint generated by
// another implementation.
func FingerprintLegacyMD5(pubKey PublicKey) string {
	return gossh.FingerprintLegacyMD5(pubKey)
}
