// Copyright 2026 malivvan. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package minisign

import (
	"bytes"
	"encoding/binary"
	"io"
	"os"
	"strings"
	"testing"

	"github.com/malivvan/crypto/blake2b"
	"github.com/malivvan/crypto/ed25519"
)

// testKey returns a deterministic wallet-style Ed25519 signing key built from
// a constant seed.
func testKey(t *testing.T, seedByte byte) *ed25519.PrivateKey {
	t.Helper()
	seed := bytes.Repeat([]byte{seedByte}, ed25519.SeedSize)
	key, err := ed25519.GenerateKeyFromSeed(seed)
	if err != nil {
		t.Fatalf("GenerateKeyFromSeed: %v", err)
	}
	return key
}

func TestSignVerify(t *testing.T) {
	key := testKey(t, 0x42)
	msg := []byte("Hello World!")

	pub := PublicKeyFromEd25519(&key.PublicKey)
	sig, err := Sign(key, msg)
	if err != nil {
		t.Fatalf("Sign: %v", err)
	}
	if sig == nil {
		t.Fatal("expected a signature")
	}
	if !Verify(pub, msg, sig) {
		t.Fatalf("Verify failed for a freshly produced signature")
	}
	if Verify(pub, []byte("tampered"), sig) {
		t.Fatalf("Verify accepted a tampered message")
	}

	// A signature produced with a different key must not verify.
	other := testKey(t, 0x24)
	if Verify(PublicKeyFromEd25519(&other.PublicKey), msg, sig) {
		t.Fatalf("Verify accepted a signature from the wrong key")
	}
}

func TestReaderSignVerify(t *testing.T) {
	key := testKey(t, 0x51)
	msg := strings.Repeat("streamed message. ", 100)

	pub := PublicKeyFromEd25519(&key.PublicKey)

	// Sign over a streaming (Reader) message.
	streamReader := NewReader(strings.NewReader(msg))
	if _, err := io.Copy(io.Discard, streamReader); err != nil {
		t.Fatalf("drain: %v", err)
	}
	sig, err := streamReader.Sign(key)
	if err != nil {
		t.Fatalf("Sign: %v", err)
	}
	if sig == nil {
		t.Fatal("expected a signature")
	}

	// Verify over an independently-read stream of the same message.
	verifyReader := NewReader(strings.NewReader(msg))
	if _, err := io.Copy(io.Discard, verifyReader); err != nil {
		t.Fatalf("drain: %v", err)
	}
	if !verifyReader.Verify(pub, sig) {
		t.Fatal("streaming Verify failed")
	}
}

// TestInteropReferenceVector verifies a signature generated by the reference
// minisign tool over the shipped message, using the shipped public key. This
// pins the wire/encoding format and Ed25519 verification against an external
// implementation, independent of this package's own signing.
func TestInteropReferenceVector(t *testing.T) {
	message, err := os.ReadFile("./testdata/message.txt")
	if err != nil {
		t.Fatalf("read message: %v", err)
	}
	pub, err := PublicKeyFromFile("./testdata/minisign.pub")
	if err != nil {
		t.Fatalf("read public key: %v", err)
	}
	sig, err := os.ReadFile("./testdata/message.txt.minisig")
	if err != nil {
		t.Fatalf("read signature: %v", err)
	}
	if !Verify(pub, message, sig) {
		t.Fatal("reference signature did not verify against reference message/public key")
	}
	if Verify(pub, message, []byte("not a signature")) {
		t.Fatal("garbage accepted as a signature")
	}
}

// TestKeyID checks that key-ID derivation uses the first eight bytes
// (little-endian) of the BLAKE2b-256 hash of the public point.
func TestKeyID(t *testing.T) {
	point := make([]byte, ed25519.PublicKeySize)
	for i := range point {
		point[i] = byte(i * 3)
	}
	sum := blake2b.Sum256(point)
	want := binary.LittleEndian.Uint64(sum[:8])
	if got := keyIDFromPublicKey(point); got != want {
		t.Fatalf("keyIDFromPublicKey: got %#x want %#x", got, want)
	}
}
